Repository mosn/mosn.io, pull requests merged in 2022-03, with the labels that each got.

#176 redirect mosn.io/holmes to github.com/mosn/holmes.
  static/holmes
Labels: cla:yes, size/XS

#177 Add extensions import path
  static/extensions/go-plugin
  static/extensions/proxy-wasm/wasm-sdk-go
Labels: cla:yes, size/S

#178 Add Index
  static/extensions/index.html
  static/extensions/proxy-wasm/index.html
Labels: cla:yes, size/S

#179 new post: how to contribute.
  content/zh/docs/dev/contribute/index.md
Labels: question, cla:yes, size/M

#180 docs: add holmes post
  content/zh/blog/posts/mosn-holmes-design/index.md
  content/zh/blog/posts/mosn-holmes-design/ring.png
  content/zh/blog/posts/mosn-holmes-design/system.png
Labels: cla:yes, First-time contributor, size/L

#181 docs:delete outdated
  content/en/docs/quick-start/proxy/index.md
  content/zh/docs/quick-start/proxy/index.md
Labels: cla:yes, size/XS

#183 enhance route configuration
  content/zh/docs/configuration/server/router/index.md
Labels: cla:yes, size/L

#182 improved the quick start: added a simple sample for running MOSN.
  content/zh/docs/quick-start/proxy/index.md
Labels: cla:yes, size/L

#188 footer: added a DingTalk QR code.
  themes/docsy/i18n/en.toml
  themes/docsy/i18n/zh.toml
  themes/docsy/layouts/partials/footer.html
Labels: cla:yes, size/S

#187 add cluster config doc and update server config doc.
  content/zh/docs/configuration/clustermanager/index.md
  content/zh/docs/configuration/server/_index.md
Labels: cla:yes, size/L
